
name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 16
      - run: npm install -y yarn
      - run: yarn install --flozen-lockfile
      - run: yarn build
