
name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 16
      - run: npm install -y yarn
      - run: yarn install --flozen-lockfile
      - run: yarn build
      - uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_S3_BUCKET: yoshs-website-s3
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1
