
name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 16
      - run: npm install -y yarn
      - run: yarn install --flozen-lockfile
      - run: yarn build
      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          aws-s3-bucket: s3://yoshs-website-s3
      - run: aws s3 sync ./out s3://yoshs-website-s3
